GET http://localhost:8000/api/subjects?
###
POST http://localhost:8000/api/auth/sign-up/email
Origin: http://localhost:5173
Content-Type: application/json

{
    "email": "john123@test.com",
    "password": "test1234",
    "name": "Johnnie123",
    "role": "teacher"
}